version: "3.9"

name: housinghelper

services:
  postgres:
    image: postgres:16-alpine
    container_name: hh-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - app_pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./back-end
    container_name: hh-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "8080:8080"


  frontend:
    build:
      context: ./front-end
    container_name: hh-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  app_pgdata:
